"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["src_presets_configs_POL_Send_TrI_NV_27_json"],{

/***/ "./src/presets/configs/POL_Send_TrI_NV_27.json":
/*!*****************************************************!*\
  !*** ./src/presets/configs/POL_Send_TrI_NV_27.json ***!
  \*****************************************************/
/***/ ((module) => {

module.exports = JSON.parse('{"morseSettings":[{"key":"wpm","value":27,"comment":null},{"key":"fwpm","value":27,"comment":null},{"key":"xtraWordSpaceDits","value":"1","comment":null},{"key":"volume","value":"4","comment":null},{"key":"stickySets","value":"BK","comment":null},{"key":"ifStickySets","value":false,"comment":null},{"key":"syncWpm","value":"true","comment":null},{"key":"hideList","value":true,"comment":null},{"key":"showRaw","value":true,"comment":null},{"key":"darkMode","value":false,"comment":null},{"key":"autoCloseSettingsAccordions","value":false,"comment":null},{"key":"autoCloseLessonAccordian","value":true,"comment":null},{"key":"ifCustomGroup","value":false,"comment":null},{"key":"customGroup","value":"","comment":null},{"key":"showExpertSettings","value":"true","comment":null},{"key":"voiceEnabled","value":false,"comment":null},{"key":"voiceSpelling","value":true,"comment":null},{"key":"voiceThinkingTime","value":"3","comment":null},{"key":"voiceAfterThinkingTime","value":"0","comment":null},{"key":"voiceVolume","value":10,"comment":null},{"key":"voiceLastOnly","value":false,"comment":null},{"key":"voiceRecap","value":false,"comment":null},{"key":"speakFirst","value":false,"comment":null},{"key":"numberOfRepeats","value":0,"comment":null},{"key":"speakFirstAdditionalWordspaces","value":6,"comment":null},{"key":"keepLines","value":true,"comment":null},{"key":"syncSize","value":true,"comment":null},{"key":"overrideSize","value":false,"comment":null},{"key":"overrideSizeMin","value":3,"comment":null},{"key":"overrideSizeMax","value":3,"comment":null},{"key":"cardSpace","value":"5","comment":"AKA cardWait"},{"key":"miscSettingsAccordionOpen","value":false,"comment":null},{"key":"speedInterval","value":false,"comment":null},{"key":"intervalTimingsText","value":"","comment":null},{"key":"intervalWpmText","value":"","comment":null},{"key":"intervalFwpmText","value":"","comment":null},{"key":"speedRacerEnabled","value":false,"comment":null},{"key":"speedRacerMultipliers","value":"1.5, 1.35, 1.175, 1.0","comment":null},{"key":"speedRacerFinalPlay","value":true,"comment":null},{"key":"speedRacerSpeakBeforeReplay","value":true,"comment":null},{"key":"speedRacerKeepFwpm","value":true,"comment":null},{"key":"voiceBufferMaxLength","value":1,"comment":null},{"key":"isShuffledSet","value":true,"comment":null},{"key":"shuffleIntraGroup","value":false,"comment":null}]}');

/***/ })

}]);