"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["src_wordfiles_POL_Bi_Pt2_txt"],{

/***/ "./src/wordfiles/POL_Bi_Pt2.txt":
/*!**************************************!*\
  !*** ./src/wordfiles/POL_Bi_Pt2.txt ***!
  \**************************************/
/***/ ((module) => {

module.exports = "AAA \r\nALL OR NOTHING \r\nACHES AND PAINS \r\nBBB \r\nBLACK AND WHITE \r\nBACK AND FORTH \r\nBRIGHT AND EARLY \r\nCCC \r\nCHECKS AND BALANCES \r\nCOPY AND PASTE \r\nCARROT AND STICK \r\nDDD \r\nDONE AND DUSTED \r\nDOS AND DONTS \r\nDOWN AND OUT \r\nEEE \r\nEVEN OR ODD \r\nEAT AND DRINK \r\nEASY OR HARD \r\nFFF \r\nFAST AND FURIOUS \r\nFACTS AND FIGURES \r\nFAR AND WIDE \r\nGGG \r\nGRIP IT AND RIP IT \r\nGRIN AND BEAR IT \r\nGOODS AND SERVICES \r\nHHH \r\nHOT AND COLD \r\nHIGHWAYS AND BYWAYS \r\nHUSTLE AND BUSTLE \r\nIII \r\nIDLE OR BUSY \r\nINS AND OUTS \r\nIRON AND BRASS \r\nJJJ \r\nJETS OR PATRIOTS \r\nJOIN OR LEAVE \r\nJACK AND JILL \r\nKKK \r\nKIT AND KABOODLE \r\nKEY OR PADDLE \r\nKIND OR KINDLY \r\nLLL \r\nLIFE OR DEATH \r\nLOUD AND CLEAR \r\nLO AND BEHOLD \r\nMMM \r\nMORE OR LESS \r\nMEET AND GREET \r\nMAN AND WIFE \r\nNNN \r\nNICE AND EASY \r\nNEAT AND TIDY \r\nNOW AND AGN \r\nOOO \r\nOVER AND OUT \r\nOUT AND ABOUT \r\nONE OR TWO \r\nPPP \r\nPICK AND CHOOSE \r\nPLAIN AND SIMPLE \r\nPROS AND CONS \r\nQQQ \r\nQUIET OR LOUD \r\nQSO AND QRS \r\nQUIT AND LEAVE \r\nRRR \r\nRICH AND POOR \r\nROUGH AND TUMBLE \r\nRISE AND FALL \r\nSSS \r\nSAFE AND SOUND \r\nSHORT AND SWEET \r\nSOONER OR LATER \r\nTTT \r\nTWISTS AND TURNS \r\nTHROUGH AND THROUGH \r\nTOIL AND TROUBLE \r\nUUU \r\nU OR ME \r\nUSER FRIENDLY OR NOT \r\nUP AND DOWN \r\nVVV \r\nVOLTS AND AMPS \r\nVAST AND WIDE \r\nVIM AND VIGOR \r\nWWW \r\nWITH OR WITHOUT \r\nWINE AND DINE \r\nWEAR AND TEAR \r\nXXX \r\nX�S AND O�S\r\nXYL IS WIFE \r\nXENIA HAMFEST \r\nYYY \r\nYES AND NO\r\nYEAR AND MONTH \r\nYOUNG AND OLD \r\nZZZ \r\nZAP THE FLY \r\nZIG OR ZAG \r\nZANY AND WILD \r\n";

/***/ })

}]);