"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["src_wordfiles_POL_3W_Phrases_Pt2_txt"],{

/***/ "./src/wordfiles/POL_3W_Phrases_Pt2.txt":
/*!**********************************************!*\
  !*** ./src/wordfiles/POL_3W_Phrases_Pt2.txt ***!
  \**********************************************/
/***/ ((module) => {

module.exports = "AAA  \r\nA PRETTY PENNY \r\nACT OF WAR \r\nAHEAD OF TIME \r\nAT FULL TILT \r\nBBB  \r\nBAG OF BONES \r\nBECK AND CALL \r\nBEHIND THE CURVE \r\nBET THE FARM \r\nCCC  \r\nCALL THE SHOTS \r\nCANT BEAT THAT \r\nCHEW THE FAT \r\nCOAST IS CLEAR \r\nDDD  \r\nDEAD CAT BOUNCE \r\nDO THE TRICK \r\nDOG EAT DOG \r\nDOWN THE HATCH \r\nEEE  \r\nEASY AS PIE \r\nEAT YOUR WORDS \r\nEASY DOES IT \r\nEARN A LIVING \r\nFFF  \r\nFOCUS AND WIN \r\nFINE TOOTH COMB \r\nFOR THE BIRDS \r\nFULL SPEED AHEAD \r\nGGG  \r\nGILD THE LILY \r\nGO FOR BROKE \r\nGRAIN OF SALT \r\nGREEN WITH ENVY \r\nHHH  \r\nHALF A MIND \r\nHEAD OVER HEELS \r\nHEART OF GOLD \r\nHIT THE HAY \r\nIII  \r\nIN A PICKLE  \r\nIN HOT WATER \r\nIVE GOT THIS \r\nJJJ  \r\nJOG MY MEMORY \r\nJUMP THE SHARK \r\nJOCKEY FOR POSITION \r\nJUMP THROUGH HOOPS \r\nKKK  \r\nKEEP IT SIMPLE \r\nKETTLE OF FISH \r\nKEEP UNDER WRAPS \r\nKEEP MOVING FORWARD \r\nLLL  \r\nLABOR OF LOVE \r\nLARGER THAN LIFE \r\nLEND AN EAR \r\nLOOK AT THIS \r\nMMM  \r\nMISS THE BOAT \r\nMUMS THE WORD \r\nMIND OVER MATTER \r\nMET YOUR MATCH \r\nNNN  \r\nNO LOVE LOST \r\nNEW YORK MINUTE \r\nNERVES OF STEEL \r\nNEVER SAY DIE \r\nOOO  \r\nON A ROLL \r\nOFF YOUR ROCKER \r\nOLDER THAN DIRT \r\nON GOOD TERMS \r\nPPP  \r\nPAY THE PIPER[ \r\nPIECE OF CAKE \r\nPRIM AND PROPER \r\nPULL THE PLUG \r\nQQQ  \r\nQUIET OR ELSE \r\nQUIT OR STAY \r\nQUICK AS LIGHTNING \r\nRRR  \r\nREST IS GRAVY \r\nROUND THE BEND \r\nRANK AND FILE \r\nRIGHT AS RAIN \r\nSSS  \r\nSHIP CAME IN \r\nSPREAD THE WORD \r\nSTACK THE DECK \r\nSLOW BUT SURE \r\nTTT  \r\nTIME AND AGAIN \r\nTHE SHORT STRAW \r\nTAKE THE FALL \r\nTOE THE LINE \r\nUUU  \r\nUP THE ANTE \r\nUP THE CREEK \r\nUNDER THE RADAR \r\nUP TO SNUFF \r\nVVV  \r\nVOTE NOW TODAY \r\nVACCINE SHOT TODAY \r\nVET THE APPLICANT \r\nVICE SQUAD CAR \r\nWWW  \r\nWALK THE TALK \r\nWALK OR RUN \r\nWORSE FOR WEAR \r\nWHY NOT NOW? \r\nXXX  \r\nXYL IS LATE \r\nXEROX THAT PAGE \r\nXENIA IN OHIO \r\nYYY  \r\nYOU AND ME \r\nYOU WILL WIN \r\nYOU ARE LOVED \r\nYOU ARE WORTHY \r\nZZZ  \r\nZIP ON DOWN \r\nZAGNUT CANDY BAR \r\nZOO OR BUST \r\nZANY BUT FUN \r\n";

/***/ })

}]);