"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["src_wordfiles_ICR10_txt"],{

/***/ "./src/wordfiles/ICR10.txt":
/*!*********************************!*\
  !*** ./src/wordfiles/ICR10.txt ***!
  \*********************************/
/***/ ((module) => {

module.exports = "TALL TALES\nCOST RATIO\nSTAIR RAIL\nEARN A REST\nA CATS TAIL\nA CORE ROLE\nLET IT REST\nTELL IT ALL\nTO TELL\nSTEER A CAR\nAN EAR CANAL\nA LATE RISER\nNOT ONE IOTA\nEASE INTO IT\nERASE IT ALL\nERICA IS NICE\nTOAST A SCONE\nA COST I LOST\nI LOST A RACE\nLEARN TO EARN\nTEAR IN A TIRE\nTRAIN TO LEARN\nA SCAN AT NOON\nEAT IT OR ELSE\nTEN CARAT STONE\nA TEN CENT LOAN\nLETS TEASE ERIC\nTOO SORE TO SIT\nLONE STAR STATE\nITS NOT REAL\nTOTAL SOLAR\nA TRACE TO A SCENT\nRAISE COSTS SOON\nSAIL ON AN OCEAN\nI CANT CARE LESS\nA SEAL SAT CLOSE\nNO SNAIL IS CLEAN\nIT IS NOT A STONE\nSAIL ON AN OCEAN \nA STAIN ON A COAT\nONE ACRE TO A LOT\nA REAL TALL CRANE\nLETS RAISE A TOAST\nRIOTS ARE NOT COOL\nALL ACRES IN A LOT\nI LOST A TEST LIST\nSLOT CARS ARE COOL\nSIT IN A TRAIN CAR\nIT IS NOT AN ERROR\nLETS RACE TO A TREE\nSORT COINS A LOT\nIT ISNT A REAL NAIL\nI CAN LEARN TO SAIL\nITS TOO LATE TO EAT\nITS A REAL RAT RACE\nA LENS CAN TEAR\nA LION IS NOT AN ANT\nCAROL ACES ALL TESTS\nA COOT SAT ON A SEAT\nITS A TREAT TO TRAIN\nAT LEAST I CAN LEARN\nITS A REAL TEST TONE\nOIL IN A CAN\nA LAST ONE CAN ROLL IN\nSCOOT INTO A REAR SEAT\nA NEAT AREA TO SAIL IN\nLIE ON A COT IN RAIN \nTIN CANS ARE IN A STORE\nLAST ONE TO LOSE A RACE\nCORN IN AN AREA\nAS I SEE IT I CAN LEARN\nRAIN OR SLEET ISNT NEAT\nI CANT STEAL TESLA TIRES\nIS IT A TALL TALE OR NOT\nLIONS CAN REACT TO NOISE\nLETS SIT ON A SEAT TO EAT\nA COOL CAT ATE A RATS TAIL\nSTAN CRIES IN CASE IT RAINS\nI CANT TAN IN RAIN OR SLEET\nRAIN NOR SLEET NOR LATE AT NITE\nTEN CENT COINS ARE AT LEAST A START\n\n\n\n";

/***/ })

}]);