"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["src_wordfiles_POL_5W_ALL_txt"],{

/***/ "./src/wordfiles/POL_5W_ALL.txt":
/*!**************************************!*\
  !*** ./src/wordfiles/POL_5W_ALL.txt ***!
  \**************************************/
/***/ ((module) => {

module.exports = "AAA \r\nAFTER \nABOUT \nAGAIN \nABOVE \nABORT \nAHEAD \nBBB \r\nBREAD \nBLAZE \nBEING \nBEGAN \nBAKED \nBALLS \nCCC \r\nCLEAR \nCOULD \nCLOUD \nCABLE \nCABIN \nCARGO \nCATCH \nDDD \r\nDELAY \nDRIFT \nDAILY \nDAZED \nDECOY \nDENSE \nEEE \r\nEARTH \nEVERY \nENTRY \nEAGER \nENTER \nEJECT \nEMPTY \nFFF \r\nFIRST \nFIELD \nFACTS \nFALSE \nFANCY \nFAULT \nFEAST \nFEVER \nGGG \r\nGRASS \nGREAT \nGAUGE \nGAUZE \nGEARS \nGLOOM \nGRADE \nHHH \r\nHOUSE \nHAPPY \nHERTZ \nHEAVY \nHEDGE \nHOBBY \nHOTEL \nHOURS \nIII \r\nINPUT \nIDEAL \nINDEX \nICONS \nINLAY \nINERT \nINNER \nISSUE \nJJJ \r\nJELLY \nJOINT \nJUDGE \nJEWEL \nJUMPY \nJUICY \nJOLLY \nKKK \r\nKNOCK \nKNIFE \nKEYER \nKNOWN \nKEYED \nKIOSK \nKHAKI \nLLL \r\nLIGHT \nLARGE \nLAYER \nLAPEL \nLEAFY \nLEARN \nLEAST \nLEAVE \nMMM \r\nMACRO \nMEANS \nMORSE \nMAJOR \nMUGGY \nMOVIE \nMOTEL \nMEMOS \nNNN \r\nNOTCH \nNOISE \nNEVER \nNIGHT \nNERVE \nNAMED \nNAÏVE \nOOO \r\nOTHER \nOZONE \nOCCUR \nOFFER \nOFTEN \nOLDER \nOUGHT \nORGAN \nOUNCE \nPPP \r\nPLACE \nPOWER \nPOINT \nPAUSE \nPEOPLE \nPEERS \nPEARL \nPERKS \nPIZZA \nPRANK \nPROOF \nQQQ \r\nQUEEN \nQUICK \nQUIET \nQUITE \nQUAKE \nQUILT \nQUEST \nQUOTA \nQUOTE \nRRR \r\nRELAY \nRIGHT \nRADIO \nROAST \nROBIN \nROOMY \nRIVER \nROBOT \nRESIN \nSSS \r\nSTILL \nSMALL \nSTATE \nSOLAR \nSHIRT \nSNIFF \nSNAKE \nSKATE \nSIXTH \nSTORM \nTTT \r\nTHERE \nTHEIR \nTHESE \nTHING \nTHINK \nTHOSE \nTWICE \nTWIST \nTRICK \nTOUCH \nTOOTH \nUUU \r\nUNITY \nUNDER \nUPPER \nUSUAL \nUSING \nUNFIT \nUNION \nUNZIP \nURBAN \nUPSET \nVVV \r\nVIVID \nVOICE \nVOWEL \nVOLTS \nVOTES \nVOTER \nVALUE \nVENOM \nVALID \nVENUE \nWWW \r\nWOULD \nWHERE \nWORLD \nWHICH \nWRONG \nWHILE \nWHITE \nWINDY \nWATCH \nXXX \r\nXYL \nXENON \nXEROX \nXENIA \nYYY \r\nYOUTH \nYIELD \nYAGIS \nYOUNG \nYEAST \nYACHT \nYAHOO \nZZZ \r\nZEBRA \nZONES \nZIPPY \nZINGY \nZESTY \nZEROS \r\n";

/***/ })

}]);