"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["src_wordfiles_ICR6_txt"],{

/***/ "./src/wordfiles/ICR6.txt":
/*!********************************!*\
  !*** ./src/wordfiles/ICR6.txt ***!
  \********************************/
/***/ ((module) => {

module.exports = "A\tI\tAT IT\tNO\tTO\tAS\tSO\tOR\tAN\tON\tIN\tIS\tANT\tTOE\tONE\tRAT\tSAT\tEAT\tSIT\tCAR\tACE\tCAT\tOAR\tSET\tARE\tSEE\tACT\tTAN\tRAN\tEEL\tNOR\tTIN\tATE\tCAN\tOIL\tILL\tLOT\tCOT\tNOT\tTEN\tLIE\tALL\tITS\tLATE\tTORN\tEARN\tSAIL\tCOIN\tTALE\tRARE\tLOST\tTOOL\tROLL\tCOOT\tSOLE\tSTAN\tASIA\tROSE\tLOSE\tACRE\tONCE\tTONE\tLESS\tTEST\tCATS\tSORT\tLACE\tNEAR\tROOT\tCENT\tRATS\tCANT\tREST\tSLOT\tLOON\tEATS\tNEAT\tELSE\tALSO\tTILT\tCORE\tLETS\tLAST\tCOST\tSOOT\tSINE\tRENT\tISNT\tIOTA\tNOON\tACES\tNOTE\tCARS\tCOAT\tREEL\tCOAL\tEASE\tSARA\tCONE\tIRON\tRACE\tRISE\tCASE\tSOIL\tNICE\tSEEN\tSORE\tTELL\tSCAN\tTIRE\tRANT\tSELL\tCOOL\tNEON\tLEAN\tTOES\tLINE\tCORN\tOATS\tAREA\tSEAL\tSOON\tCITE\tOARS\tREAR\tTOSS\tLION\tTALL\tTART\tCOIL\tNOSE\tLOTS\tSALE\tSANE\tTENT\tLONE\tCARE\tRAIL\tCANE\tTEAR\tTREE\tTOTE\tCANS\tLOAN\tLENS\tLIST\tSEAT\tSTAR\tRAIN\tNAIL\tROAR\tREAL\tRIOT\tTAIL\tCOINS\tSTAIN\tCONES\tINLET\tTACIT\tREACT\tCRIES\tTILES\tOTTER\tTENTS\tRATES\tRISES\tCEASE\tCLONE\tTENSE\tCOLOR\tCRANE\tSCONE\tSCANS\tCANES\tLATIN\tSTATE\tOCEAN\tSLANT\tRAILS\tSTEAL\tSTART\tRACES\tSTAIR\tOSCAR\tLINES\tCELLS\tREINS\tCELLO\tTESTS\tARENT\tRISER\tROAST\tLISTS\tERICA\tERROR\tROLES\tNOISE\tSEALS\tSTOLE\tERASE\tROARS\tSNEER\tRAISE\tCOATS\tLOANS\tTACOS\tSTALL\tTREAT\tATTIC\tCANOE\tTALES\tRETRO\tLIONS\tLOSER\tTRAIN\tLATER\tIRONS\tCOSTS\tRACER\tCANAL\tTAILS\tACRES\tSTARS\tTRACE\tSTILL\tTOTAL\tRATIO\tSOLAR\tTONES\tSNAIL\tAREAS\tSCARE\tRESET\tCLEAR\tSCENT\tTIRES\tCLEAN\tCARAT\tCAROL\tSATIN\tTITLE\tNOTES\tTEASE\tLEAST\tCLASS\tSENSE\tRAINS\tCLOSE\tRIOTS\tTOAST\tEASEL\tSTORE\tLEARN\tTRAIL\tROOTS\tSTONE\tRELIC\tTENOR\tACTOR\tTESLA\tSLEET\tSTEER\tRINSE\tSLICE\tSIREN\n";

/***/ })

}]);