"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["src_wordfiles_First_Only_txt"],{

/***/ "./src/wordfiles/First Only.txt":
/*!**************************************!*\
  !*** ./src/wordfiles/First Only.txt ***!
  \**************************************/
/***/ ((module) => {

module.exports = "\r\nPRECISION {ENTERTAIN|} \r\n{|PRECISIONENTERTAIN} \r\nSEPARATE {PARAGRAPH|} \r\n{|SEPARATEPARAGRAPH} \r\nPARTICULAR {TEMPERATURE|} \r\n{|PARTICULARTEMPERATURE} \r\nTRIANGLE {MATERIAL|} \r\n{|TRIANGLEMATERIAL} \r\nPOSSIBLE {QUESTION|} \r\n{|POSSIBLEQUESTION} \r\nCOMPLETE {EXPERIENCE|} \r\n{|COMPLETEEXPERIENCE} \r\nTHOUSAND {MOUNTAINS|} \r\n{|THOUSANDMOUNTAINS} \r\nNECESSARY {EXPERIMENT|} \r\n{|NECESSARYEXPERIMENT} \r\nDIFFICULT {SOLUTION|} \r\n{|DIFFICULTSOLUTION} \r\nMULTIPLY {FRACTIONS|} \r\n{|MULTIPLYFRACTIONS} \r\nLANGUAGE {DICTIONARY|} \r\n{|LANGUAGEDICTIONARY} \r\nOPPOSITE {CONDITION|} \r\n{|OPPOSITECONDITION} \r\nELECTRIC {SUBSTANCE|} \r\n{|ELECTRICSUBSTANCE} \r\nREMEMBER {CHILDREN|} \r\n{|REMEMBERCHILDREN} \r\nSUBTRACT {MATERIAL|} \r\n{|SUBTRACTMATERIAL} \r\nINDICATE {CONDITION|} \r\n{|INDICATECONDITION} \r\nEXERCISE {RESTRAINT|} \r\n{|EXERCISERESTRAINT} \r\nINSTRUMENT {EXPERIMENT|} \r\n{|INSTRUMENTEXPERIMENT} \r\nCONSIDER {PRACTICE|} \r\n{|CONSIDERPRACTICE} \r\nREPRESENT {NECESSITY|} \r\n{|REPRESENTNECESSITY} \r\nCHARACTER {REFERENCE|} \r\n{|CHARACTERREFERENCE} \r\nNEIGHBORHOOD {SURPRISE|} \r\n{|NEIGHBORHOODSURPRISE} \r\nPROPERTY {DIVISION|} \r\n{|PROPERTYDIVISION} \r\nPROBABLE {POSITION|} \r\n{|PROBABLEPOSITION} \r\nINTEREST {SUBTRACTION|} \r\n{|INTERESTSUBTRACTION} \r\nESPECIALLY {DIFFICULT|} \r\n{|ESPECIALLYDIFFICULT} \r\n\r\n";

/***/ })

}]);