"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["src_wordfiles_PWB1_txt"],{

/***/ "./src/wordfiles/PWB1.txt":
/*!********************************!*\
  !*** ./src/wordfiles/PWB1.txt ***!
  \********************************/
/***/ ((module) => {

module.exports = "O\tOK\nD\tDR\tDRY\nO\tOL\tOLD\nM\tMO\tMOM\nR\tRO\tROW\nL\tLE\tLET\t\nG\tGO\tGOD\t\nK\tKI\tKID\t\nM\tMI\tMIX\t\nW\tWH\tWHO\t\nB\tBY\t\nS\tSE\tSEE\t\nB\tBY\tBYE\t\nA\tAR\tART\t\nT\tTR\tTRY\t\nJ\tJA\tJAM\t\nC\tCA\tCAR\t\nB\tBA\tBAR\t\nG\tGA\tGAS\nF\tFR\tFRY\nF\tFU\tFUN\nF\tFI\tFIX\nD\tDO\t\nT\tTV\t\nT\tTI\tTIE\nF\tFA\tFAR\t\nS\tSU\tSUN\t\nB\tBU\tBUY\t\nD\tDA\tDAY\t\nR\tRA\tRAW\t\nT\tTI\tTIP\t\nH\tHE\nL\tLA\tLAB\t\nW\tWE\tWEB\t\nO\tOF\tOFF\t\nY\tYE\tYET\t\nI\t\nP\tPE\tPET\t\nI\tIN\t\nS\tSH\tSHE\t\nN\tNU\tNUT\t\nJ\tJO\tJOY\t\nS\tSA\tSAD\t\nP\tPI\tPIG\t\nL\tLA\tLAY\t\nA\tAI\tAIR\t\nW\tWA\tWAR\t\nH\tHO\tHOT\t\nO\tOD\tODD\t\nY\tYE\tYES\t\nM\tMA\tMAD\t\nF\tFL\tFLU\t\nO\tOR\t\nC\tCA\tCAN\t\nC\tCO\tCOW\t\nO\tOU\tOUR\t\nB\tBE\t\nO\tOI\tOIL\t\nB\tBO\tBOY\t\nT\tTE\tTEA\t\nB\tBI\tBID\t\nT\tTO\t\nO\tON\t\nW\tWI\tWIN\t\nO\tOF\t\nU\tUS\tUSE\t\nI\tIT\tITS\t\nD\tDA\tDAD\t\nS\tSE\tSEX\t\nA\tAD\tADD\t\nB\tBA\tBAG\t\nH\tHO\tHOW\t\nF\tFO\tFOR\t\nI\tIC\tICE\t\nT\tTW\tTWO\t\nP\tPO\tPOT\t\nK\tKE\tKEY\t\nT\tTE\tTEN\t\nB\tBI\tBIG\t\nY\tYO\tYOU\t\nE\tEG\tEGG\t\nA\tAL\tALL\t\nM\tMA\tMAN\t\nC\tCD\t\nH\tHI\t\nI\tIT\t\nD\tDI\tDIG\t\nP\tPU\tPUT\t\nB\tBE\tBED\t\nM\tME\t\nF\tFU\tFUR\t\nS\tSO\t\nB\tBI\tBIT\nB\tBE\tBEG\t\nA\tAC\tACT\t\nA\tAD\t\nA\tAR\tARM\t\nP\tPO\tPOP\t\nS\tSH\tSHY\t\nB\tBA\tBAD\t\nH\tHI\tHIS\t\nL\tLE\tLEG\t\nA\tAN\tAND\t\nN\tNO\tNOW\t\nC\tCR\tCRY\t\nC\tCA\tCAP\t\nR\tRE\tRED\t\nJ\tJO\tJOB\t\nD\tDO\tDOG\t\nA\tAG\tAGE\t\nE\tEA\tEAR\t\nL\tLA\tLAW\t\nN\tNO\tNOR\t\nB\tBA\tBAN\t\nE\tEA\tEAT\t\nM\tMY\t\nP\tPA\tPAY\t\nS\tSK\tSKI\t\nC\tCU\tCUT\t\nH\tHI\tHIM\t\nG\tGA\tGAP\t\nG\tGU\tGUN\t\nR\tRI\tRID\t\nS\tSU\tSUM\t\nS\tSI\tSIX\t\nW\tWE\t\nR\tRU\tRUN\t\nV\tVI\tVIA\t\nP\tPE\tPER\t\nA\tAI\tAID\t\nT\tTO\tTOE\t\nB\tBE\tBEE\t\nS\tSE\tSEA\t\nS\tSO\tSON\t\nM\tMU\tMUD\t\nF\tFL\tFLY\t\nG\tGY\tGYM\t\nA\tAT\t\nA\tAS\tASK\t\nL\tLO\tLOW\t\nT\tTO\tTON\t\nA\tAH\t\nA\tAN\t\nA\tAP\tAPP\nO\tOU\tOUT\t\nS\tSE\tSET\t\nT\tTO\tTOP\t\nN\tNE\tNET\t\nD\tDV\tDVD\t\nA\tAN\tANY\t\nE\tEN\tEND\t\nN\tNE\tNEW\t\nG\tGE\tGET\t\nP\tPI\tPIN\t\nB\tBU\tBUS\t\nO\tOW\tOWN\t\nG\tGU\tGUY\t\nF\tFA\tFAN\t\nF\tFA\tFAT\t\nU\tUS\t\nE\tEY\tEYE\t\nG\tGO\t\nD\tDI\tDIE\t\nC\tCU\tCUP\t\nF\tFI\tFIT\t\nA\tAS\t\nW\tWA\tWAY\t\nO\tON\tONE\t\nB\tBU\tBUT\t\nU\tUP\t\nS\tSK\tSKY\t\nB\tBE\tBET\t\nD\tDU\tDUE\t\nT\tTA\tTAX\t\nP\tPA\tPAN\t\nI\tIF\t\nB\tBO\tBOX\t\nL\tLI\tLIP\t\nL\tLI\tLIE\t\nH\tHA\tHAT\t\nR\tRU\tRUB\t\nO\tOW\tOWE\t\nA\t\nC\tCA\tCAT\t\nT\tTO\tTOY\t\nA\tAG\tAGO\t\nH\tHE\tHEY\t\nT\tTO\tTOO\t\nH\tHI\tHIT\t\nW\tWO\tWOW\t\nV\tVA\tVAN\t\nI\tIL\tILL\t\nF\tFE\tFEW\t\nL\tLO\tLOT\t\nH\tHE\tHER\t\nP\tPE\tPEN\t\nM\tMA\tMAP\t\nW\tWE\tWET\t\nN\tNO\t\nM\tMA\tMAY\t\nW\tWH\tWHY\t\nS\tSI\tSIR\t\nF\tFE\tFEE\t\nT\tTH\tTHE\t\nO\tOH\t\nN\tNO\tNOT\t\nS\tSA\tSAY\t\nA\tAI\tAIM\t\nS\tSI\tSIT\t\n";

/***/ })

}]);