"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["src_wordfiles_POL_S_Phrases_Pt2_txt"],{

/***/ "./src/wordfiles/POL_S_Phrases_Pt2.txt":
/*!*********************************************!*\
  !*** ./src/wordfiles/POL_S_Phrases_Pt2.txt ***!
  \*********************************************/
/***/ ((module) => {

module.exports = "{AAA |AAA |1}  {AN OLD MIC |AN OLD MIC |1}  {ANT INV VEE |ANT INV VEE |1}  {BBB |BBB |2}  {BE THE ONE |BE THE ONE |2}  {BY THE TIME |BY THE TIME |2}  {CCC |CCC |3}  {CAT IS OUT |CAT IS OUT |3}  {CAN HE RUN |CAN HE RUN |3}  {DDD |DDD |4}  {DO NOT GO |DO NOT GO |4}  {DONT DO THAT |DONT DO THAT |4}  {EEE |EEE |5}  {END FED ANT |END FED ANT |5}  {EAT MORE ELK |EAT MORE ELK |5}  {FFF |FFF |6}  {FEED MY PIG |FEED MY PIG |6}  {FEEL LOST NOW |FEEL LOST NOW |6}  {GGG |GGG |7}  {GET A NAP |GET A NAP |7}  {GOT THE STORY  |GOT THE STORY  |7}  {HHH |HHH |8}  {HOT FOR NOW |HOT FOR NOW |8}  {HIT THE SACK |HIT THE SACK |8}  {III |III |9}  {I DID WELL |I DID WELL |9}  {ITS NOT DUE |ITS NOT DUE |9}  {JJJ |JJJ |10}  {JAR OF JAM |JAR OF JAM |10}  {JUST FOR FUN |JUST FOR FUN |10}  {KKK |KKK |11}  {KEPT IT ALL |KEPT IT ALL |11}  {KEG IS FULL |KEG IS FULL |11}  {LLL |LLL |12}  {LET IT GO |LET IT GO |12}  {LIVE IT NOW |LIVE IT NOW |12}  {MMM |MMM |13}  {MUD ON RUG |MUD ON RUG |13}  {MY TIN CUP |MY TIN CUP |13}  {NNN |NNN |14}  {NEW TO ME |NEW TO ME |14}  {NOW ITS OVER |NOW ITS OVER |14}  {OOO |OOO |15}  {OUR OLD RUG |OUR OLD RUG |15}  {OWN THE VAN |OWN THE VAN |15}  {PPP |PPP |16}  {PAL OF MINE |PAL OF MINE |16}  {PAINT THE WALL |PAINT THE WALL |16}  {QQQ |QQQ |17}  {QUIP WAS GOOD |QUIP WAS GOOD |17}  {QUIT IT NOW |QUIT IT NOW |17}  {RRR |RRR |18}  {RIP IT OFF |RIP IT OFF |18}  {RUN FOR IT |RUN FOR IT |18}  {SSS |SSS |19}  {SHE CAN WAIT |SHE CAN WAIT |19}  {SIX TON VAN |SIX TON VAN |19}  {TTT |TTT |20}  {THE TIN MAN |THE TIN MAN |20}  {TIP TOP JOB |TIP TOP JOB |20}  {UUU |UUU |21}  {UP TO NOW |UP TO NOW |21}  {USE IT UP |USE IT UP |21}  {VVV |VVV |22}  {VAN FOR SIX |VAN FOR SIX |22}  {VISA CARD BILL |VISA CARD BILL |22}  {WWW |WWW |23}  {WHO ARE YOU |WHO ARE YOU |23}  {WAX THE CAR  |WAX THE CAR  |23}  {XXX |XXX |24}  {XYL IS HERE |XYL IS HERE |24}  {XRAYS ARE FUN |XRAYS ARE FUN |24}  {YYY |YYY |25}  {YARD IS BIG |YARD IS BIG |25}  {YOU CAN PAY |YOU CAN PAY |25}  {ZZZ |ZZZ |26}  {ZIP THE COAT |ZIP THE COAT |26}  {ZOOM ROOM LINK |ZOOM ROOM LINK |26}  {||}   \r\n";

/***/ })

}]);