"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["src_wordfiles_INT11_txt"],{

/***/ "./src/wordfiles/INT11.txt":
/*!*********************************!*\
  !*** ./src/wordfiles/INT11.txt ***!
  \*********************************/
/***/ ((module) => {

module.exports = "PRO = PROVIDES, PROJECT, PROBLEMS, PROVIDE =\nCON = CONTENT, CONTACTS, CONTRACT, CONTEXT =\nCOM = COMMENT, COMES, COMPARE, COMMENTS =\nTHE = THERE, THEME, THEIR, THEATER =\nSTA = STATE, START, STATS, STATES =\nRES = RESORT, RESERVE, RESORTS, RESPECT =\nINT = INTER, INTERNET, INTERNAL, INTEL =\nSHO = SHOWS, SHOES, SHOPS, SHOWER=\nWOR = WORKS, WORDS, WORSE, WORLDS =\nPAR = PARTS, PARTIES, PARENT, PARIS =\nFOR = FOREST, FORMS, FORCE, FORMER =\nPLA = PLANET, PLATE, PLACE, PLANT =\nPRE = PRESENT, PREVENT, PRESS, PRESSURE =\nDIS = DISASTER, DISEASE, DISTANCE, DISPUTE =\nREA = READS, READY, REACHED, READER =\nREP = REPLIED, REPLACE, REPAIR, REPLACED =\nSTO = STORE, STORED, STORIES, STONE =\nSPE = SPECS, SPECIAL, SPEAK, SPECIALS =\nEXP = EXPERT, EXPENSE, EXPOSED, EXPLORE =\nREL = RELATE, RELEASE, RELATIVE, RELEASED =\nSTR = STRING, STRANGE, STRENGTH, STRONG =\nSUR = SURVEY, SURELY, SURREY, SURVIVE =\nREF = REFER, REFUSE, REFUSED, REFINE =\nTRI = TRIES, TRIBE, TRIAL, TRIPLE =\n";

/***/ })

}]);