"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["src_wordfiles_ICR10_txt"],{

/***/ "./src/wordfiles/ICR10.txt":
/*!*********************************!*\
  !*** ./src/wordfiles/ICR10.txt ***!
  \*********************************/
/***/ ((module) => {

module.exports = "TALL TALES\r\nCOST RATIO\r\nSTAIR RAIL\r\nEARN A REST\r\nA CATS TAIL\r\nA CORE ROLE\r\nLET IT REST\r\nTELL IT ALL\r\nTO TELL\r\nSTEER A CAR\r\nAN EAR CANAL\r\nA LATE RISER\r\nNOT ONE IOTA\r\nEASE INTO IT\r\nERASE IT ALL\r\nERICA IS NICE\r\nTOAST A SCONE\r\nA COST I LOST\r\nI LOST A RACE\r\nLEARN TO EARN\r\nTEAR IN A TIRE\r\nTRAIN TO LEARN\r\nA SCAN AT NOON\r\nEAT IT OR ELSE\r\nTEN CARAT STONE\r\nA TEN CENT LOAN\r\nLETS TEASE ERIC\r\nTOO SORE TO SIT\r\nLONE STAR STATE\r\nITS NOT REAL\r\nTOTAL SOLAR\r\nA TRACE TO A SCENT\r\nRAISE COSTS SOON\r\nSAIL ON AN OCEAN\r\nI CANT CARE LESS\r\nA SEAL SAT CLOSE\r\nNO SNAIL IS CLEAN\r\nIT IS NOT A STONE\r\nSAIL ON AN OCEAN \r\nA STAIN ON A COAT\r\nONE ACRE TO A LOT\r\nA REAL TALL CRANE\r\nLETS RAISE A TOAST\r\nRIOTS ARE NOT COOL\r\nALL ACRES IN A LOT\r\nI LOST A TEST LIST\r\nSLOT CARS ARE COOL\r\nSIT IN A TRAIN CAR\r\nIT IS NOT AN ERROR\r\nLETS RACE TO A TREE\r\nSORT COINS A LOT\r\nIT ISNT A REAL NAIL\r\nI CAN LEARN TO SAIL\r\nITS TOO LATE TO EAT\r\nITS A REAL RAT RACE\r\nA LENS CAN TEAR\r\nA LION IS NOT AN ANT\r\nCAROL ACES ALL TESTS\r\nA COOT SAT ON A SEAT\r\nITS A TREAT TO TRAIN\r\nAT LEAST I CAN LEARN\r\nITS A REAL TEST TONE\r\nOIL IN A CAN\r\nA LAST ONE CAN ROLL IN\r\nSCOOT INTO A REAR SEAT\r\nA NEAT AREA TO SAIL IN\r\nLIE ON A COT IN RAIN \r\nTIN CANS ARE IN A STORE\r\nLAST ONE TO LOSE A RACE\r\nCORN IN AN AREA\r\nAS I SEE IT I CAN LEARN\r\nRAIN OR SLEET ISNT NEAT\r\nI CANT STEAL TESLA TIRES\r\nIS IT A TALL TALE OR NOT\r\nLIONS CAN REACT TO NOISE\r\nLETS SIT ON A SEAT TO EAT\r\nA COOL CAT ATE A RATS TAIL\r\nSTAN CRIES IN CASE IT RAINS\r\nI CANT TAN IN RAIN OR SLEET\r\nRAIN NOR SLEET NOR LATE AT NITE\r\nTEN CENT COINS ARE AT LEAST A START\r\n\r\n\r\n\r\n";

/***/ })

}]);