"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["src_wordfiles_INT11_txt"],{

/***/ "./src/wordfiles/INT11.txt":
/*!*********************************!*\
  !*** ./src/wordfiles/INT11.txt ***!
  \*********************************/
/***/ ((module) => {

module.exports = "PRO = PROVIDES, PROJECT, PROBLEMS, PROVIDE, PRODUCT, PROFILE, PROCESS, PROPERTY =\r\nCON = CONTENT, CONTACTS, CONTRACT, CONTEXT, CONFERENCE, CONSUMER, CONDITIONS =\r\nCOM = COMMENT, COMES, COMPARE, COMMENTS, COMPANY, COMMUNITY, COMPUTER, COMPLETE =\r\nTHE = THERE, THEME, THEIR, THEATER, THEORY, THERAPY, THEREFORE, THEMSELVES =\r\nSTA = STATE, START, STATS, STATES, STANDARD, STATUS, STAR, STATEMENT, STANDARDS =\r\nRES = RESORT, RESERVE, RESORTS, RESPECT, RESEARCH, RESOURCES, RESTAURANT, RESPONSE =\r\nINT = INTER, INTERNET, INTERNAL, INTEL, INTRODUCTION, INTO, INTEREST, INTERFACE =\r\nSHO = SHOWS, SHOES, SHOPS, SHOWER, SHORT, SHOULD, SHOWING, SHOT =\r\nWOR = WORKS, WORDS, WORSE, WORLDS, WORKERS, WORRY, WORLDWIDE, WORTH, WORKED =\r\nPAR = PARTS, PARTIES, PARENT, PARIS, PARTICULAR, PARTNERS, PARK =\r\nFOR = FOREST, FORMS, FORCE, FORMER, FORUM, FORMAT, FOREIGN, FORWARD =\r\nPLA = PLANET, PLATE, PLACE, PLANT, PLAYER, PLANNING, PLAN =\r\nPRE = PRESENT, PREVENT, PRESS, PRESSURE, PREVIOUS, PRESIDENT, PRETTY, PREMIUM =\r\nDIS = DISASTER, DISEASE, DISTANCE, DISPUTE, DISPLAY, DISTRICT, DISCOUNT, DISCUSS =\r\nREA = READS, READY, REACHED, READER, REALLY, REASONS, REACH =\r\nREP = REPLIED, REPLACE, REPAIR, REPLACED, REPORT, REPUBLIC, REPRESENTATIVE =\r\nSTO = STORE, STORED, STORIES, STONE, STOCK, STORAGE, STOP, STONE, STORM =\r\nSPE = SPECS, SPECIAL, SPEAK, SPECIALS, SPECIFIC, SPEED, SPEECH, SPENT =\r\nEXP = EXPERT, EXPENSE, EXPOSED, EXPLORE, EXPRESS, EXPECT, EXPRESSION, EXPLAIN =\r\nREL = RELATE, RELEASE, RELATIVE, RELEASED, RELATIONSHIP, RELEVANT =\r\nSTR = STRING, STRANGE, STRENGTH, STRONG, STREET, STRUCTURE, STRATEGY, STRAIGHT =\r\nSUR = SURVEY, SURELY, SURVIVE, SURE, SURFACE, SURROUND, SURF, SURPRISE =\r\nREF = REFER, REFUSE, REFUSED, REFINE, REFLECT, REFORM, REFUND, REFINE =\r\nTRI = TRIES, TRIBE, TRIAL, TRIPLE, TRIPS, TRIPLE, TRIM, TRICKS, TRIBUNE =\r\n";

/***/ })

}]);